
tasks:
  - init: docker pull  quay.io/keycloak/keycloak:15.0.1 && pip install -r requirements.txt && python create_client_secrets.py && python keycloak_admin.py && eval $(gp env -e OVERWRITE_REDIRECT_URI=$(gp url 5000)/oidc_callback)
    command: docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e PROXY_ADDRESS_FORWARDING=true quay.io/keycloak/keycloak:15.0.1

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    visibility: public
  - port: 5000
    visibility: public
vscode:
  extensions:
    - pkief.material-icon-theme
    - almenon.arepl
