
tasks:
  - init: docker pull  quay.io/keycloak/keycloak:15.0.1 && pip install -r requirements.txt
    command: docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e PROXY_ADDRESS_FORWARDING=true quay.io/keycloak/keycloak:15.0.1

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

vscode:
  extensions:
    - pkief.material-icon-theme